import React, { useState, useEffect } from 'react';
import { SupabaseCredentials } from '../types';
import { supabaseService } from '../services/supabaseService';
import { geminiService } from '../services/geminiService';

interface Props {
  creds: SupabaseCredentials;
}

interface ColumnConfig {
  id: string;
  name: string;
  type: string;
  isPk: boolean;
  isNullable: boolean;
  defaultValue: string;
  constraints: string; // UNIQUE, REFERENCES table(id), CHECK (...)
}

const COMMON_TYPES = [
  'bigint', 'integer', 'text', 'varchar', 'boolean', 'uuid', 'jsonb', 'timestamptz', 'date', 'numeric'
];

export const DatabaseManager: React.FC<Props> = ({ creds }) => {
  const [query, setQuery] = useState('');
  const [results, setResults] = useState<any[]>([]);
  const [tables, setTables] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [aiPrompt, setAiPrompt] = useState('');
  const [generating, setGenerating] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');

  // Create Table Modal State
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);
  const [newTableName, setNewTableName] = useState('');
  const [newColumns, setNewColumns] = useState<ColumnConfig[]>([
    { id: '1', name: 'id', type: 'bigint', isPk: true, isNullable: false, defaultValue: 'generated by default as identity', constraints: '' },
    { id: '2', name: 'created_at', type: 'timestamptz', isPk: false, isNullable: false, defaultValue: 'now()', constraints: '' }
  ]);
  const [tableConstraints, setTableConstraints] = useState(''); // New state for table-level constraints
  const [creatingTable, setCreatingTable] = useState(false);

  // Initial load of tables
  useEffect(() => {
    fetchTables();
  }, [creds]);

  const fetchTables = async () => {
    try {
        const sql = `SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' ORDER BY table_name;`;
        const res = await supabaseService.executeSql(creds, sql);
        setTables(res.map((r: any) => r.table_name));
    } catch (e) {
        console.error("Failed to fetch tables", e);
    }
  };

  const handleRunQuery = async () => {
    if (!query.trim()) return;
    setLoading(true);
    setError(null);
    setResults([]);
    
    try {
      const res = await supabaseService.executeSql(creds, query);
      setResults(res);
      // If it was a DDL statement, refresh tables
      if (query.toUpperCase().includes('CREATE TABLE') || query.toUpperCase().includes('DROP TABLE')) {
          fetchTables();
      }
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleAiGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!aiPrompt.trim()) return;
    setGenerating(true);
    try {
        const sql = await geminiService.generateSql(aiPrompt);
        setQuery(sql);
        setAiPrompt('');
    } catch (err) {
        setError("AI Generation failed");
    } finally {
        setGenerating(false);
    }
  };

  const handleTableClick = (tableName: string) => {
      setQuery(`SELECT * FROM ${tableName} LIMIT 20;`);
  };

  // Create Table Helpers
  const addColumn = () => {
    setNewColumns([...newColumns, { 
      id: Math.random().toString(36).substr(2, 9), 
      name: '', 
      type: 'text', 
      isPk: false, 
      isNullable: true, 
      defaultValue: '',
      constraints: ''
    }]);
  };

  const removeColumn = (id: string) => {
    if (newColumns.length <= 1) return;
    setNewColumns(newColumns.filter(c => c.id !== id));
  };

  const updateColumn = (id: string, field: keyof ColumnConfig, value: any) => {
    setNewColumns(newColumns.map(c => c.id === id ? { ...c, [field]: value } : c));
  };

  const handleCreateTableSubmit = async (e: React.FormEvent) => {
      e.preventDefault();
      if (!newTableName.trim()) {
          alert("Please enter a table name");
          return;
      }
      setCreatingTable(true);

      try {
        const colDefs = newColumns.map(c => {
            const parts = [c.name || 'unnamed_column', c.type];
            if (!c.isNullable) parts.push('NOT NULL');
            if (c.defaultValue.trim()) parts.push(`DEFAULT ${c.defaultValue}`);
            if (c.isPk) parts.push('PRIMARY KEY');
            if (c.constraints.trim()) parts.push(c.constraints);
            return '  ' + parts.join(' ');
        });

        let sqlBody = colDefs.join(',\n');
        if (tableConstraints.trim()) {
            sqlBody += ',\n  ' + tableConstraints.trim();
        }

        const sql = `CREATE TABLE public.${newTableName.trim()} (\n${sqlBody}\n);`;
        
        await supabaseService.executeSql(creds, sql);
        
        setQuery(sql);
        setResults([{ message: `Table '${newTableName}' created successfully.` }]);
        await fetchTables();
        
        // Reset and close
        setIsCreateModalOpen(false);
        setNewTableName('');
        setTableConstraints('');
        setNewColumns([
            { id: '1', name: 'id', type: 'bigint', isPk: true, isNullable: false, defaultValue: 'generated by default as identity', constraints: '' },
            { id: '2', name: 'created_at', type: 'timestamptz', isPk: false, isNullable: false, defaultValue: 'now()', constraints: '' }
        ]);

      } catch (err: any) {
          alert(`Failed to create table: ${err.message}`);
      } finally {
          setCreatingTable(false);
      }
  };

  const filteredTables = tables.filter(t => t.toLowerCase().includes(searchTerm.toLowerCase()));

  return (
    <div className="h-[calc(100vh-100px)] flex flex-col gap-6 animate-in fade-in duration-500">
       <div className="flex justify-between items-center">
            <div>
            <h2 className="text-3xl font-bold text-white tracking-tight">Database & Tables</h2>
            <p className="text-supa-400 mt-1">Execute SQL to Create, Insert, Update, and Delete.</p>
            </div>
       </div>

       <div className="flex flex-1 gap-6 min-h-0">
            {/* Sidebar: Tables List */}
            <div className="w-64 bg-supa-950 border border-supa-800 rounded-xl overflow-hidden flex flex-col">
                <div className="p-4 border-b border-supa-800 bg-supa-900 flex flex-col gap-3">
                    <div className="flex justify-between items-center">
                        <h3 className="font-bold text-supa-200 text-sm uppercase tracking-wider">Public Tables</h3>
                        <button 
                            onClick={() => setIsCreateModalOpen(true)}
                            className="bg-supa-800 hover:bg-supa-700 text-supa-200 hover:text-white p-1 px-2 rounded text-xs transition-colors"
                            title="New Table"
                        >
                            + New
                        </button>
                    </div>
                    <input
                        type="text"
                        placeholder="Search tables..."
                        value={searchTerm}
                        onChange={(e) => setSearchTerm(e.target.value)}
                        className="w-full bg-supa-950 border border-supa-700 rounded px-3 py-1.5 text-xs text-white focus:outline-none focus:border-supa-accent"
                    />
                </div>
                <div className="flex-1 overflow-y-auto p-2 space-y-1">
                    {filteredTables.map(t => (
                        <button 
                            key={t}
                            onClick={() => handleTableClick(t)}
                            className="w-full text-left px-3 py-2 rounded text-supa-400 hover:bg-supa-800 hover:text-white transition-colors text-sm font-mono flex items-center gap-2"
                        >
                            <span className="opacity-50">#</span> {t}
                        </button>
                    ))}
                    {filteredTables.length === 0 && (
                        <div className="p-4 text-xs text-supa-600 italic">
                            {tables.length === 0 ? 'No tables found in public schema.' : 'No matching tables found.'}
                        </div>
                    )}
                </div>
            </div>

            {/* Main Area: SQL Editor & Results */}
            <div className="flex-1 flex flex-col gap-4 min-w-0">
                {/* Editor Container */}
                <div className="flex-1 bg-supa-950 border border-supa-800 rounded-xl overflow-hidden flex flex-col shadow-xl">
                    {/* Toolbar / AI Prompt */}
                    <div className="p-2 border-b border-supa-800 bg-supa-900 flex gap-2 items-center">
                        <div className="flex-1 relative">
                            <form onSubmit={handleAiGenerate} className="flex gap-2">
                                <input 
                                    type="text" 
                                    placeholder="Ask AI to write SQL (e.g. 'Create a table for products with price')"
                                    value={aiPrompt}
                                    onChange={(e) => setAiPrompt(e.target.value)}
                                    className="w-full bg-supa-950 border border-supa-700 rounded px-3 py-1.5 text-sm text-white focus:border-supa-accent focus:outline-none pl-8"
                                />
                                <span className="absolute left-2.5 top-1.5 text-supa-accent">✨</span>
                                <button 
                                    type="submit"
                                    disabled={generating}
                                    className="bg-supa-800 hover:bg-supa-700 text-supa-200 px-3 py-1.5 rounded text-xs font-bold transition-colors disabled:opacity-50"
                                >
                                    {generating ? 'Writing...' : 'Generate'}
                                </button>
                            </form>
                        </div>
                        <button 
                            onClick={handleRunQuery}
                            disabled={loading}
                            className="bg-supa-accent hover:bg-supa-accentDark text-supa-950 px-6 py-1.5 rounded font-bold text-sm flex items-center gap-2 transition-all"
                        >
                            {loading ? <span className="animate-spin">↻</span> : '▶'} Run
                        </button>
                    </div>

                    {/* Textarea */}
                    <textarea 
                        value={query}
                        onChange={(e) => setQuery(e.target.value)}
                        className="flex-1 bg-supa-950 p-4 font-mono text-sm text-green-400 focus:outline-none resize-none leading-relaxed"
                        placeholder="SELECT * FROM ..."
                        spellCheck={false}
                    />
                </div>

                {/* Results Container */}
                <div className="h-1/2 bg-supa-950 border border-supa-800 rounded-xl overflow-hidden flex flex-col">
                     <div className="p-2 border-b border-supa-800 bg-supa-900 flex justify-between items-center">
                        <span className="text-xs font-bold text-supa-400 uppercase tracking-wider px-2">Results</span>
                        {results.length > 0 && <span className="text-xs text-supa-500 px-2">{results.length} rows</span>}
                     </div>
                     
                     <div className="flex-1 overflow-auto p-0 relative">
                        {error ? (
                            <div className="absolute inset-0 p-4 text-red-400 font-mono text-sm whitespace-pre-wrap">
                                {error}
                            </div>
                        ) : results.length > 0 ? (
                            <table className="w-full text-left border-collapse">
                                <thead className="bg-supa-900 sticky top-0">
                                    <tr>
                                        {Object.keys(results[0]).map(key => (
                                            <th key={key} className="p-3 text-xs font-medium text-supa-400 font-mono border-b border-supa-800">{key}</th>
                                        ))}
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-supa-800">
                                    {results.map((row, i) => (
                                        <tr key={i} className="hover:bg-supa-900/50 transition-colors">
                                            {Object.values(row).map((val: any, j) => (
                                                <td key={j} className="p-3 text-xs text-supa-200 font-mono border-r border-supa-800 last:border-r-0 whitespace-nowrap overflow-hidden text-ellipsis max-w-[200px]">
                                                    {typeof val === 'object' ? JSON.stringify(val) : String(val)}
                                                </td>
                                            ))}
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        ) : (
                            <div className="flex h-full items-center justify-center text-supa-600 text-sm italic">
                                {loading ? 'Executing...' : 'No results to display'}
                            </div>
                        )}
                     </div>
                </div>
            </div>
       </div>

       {/* Create Table Modal */}
       {isCreateModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4">
            <div className="bg-supa-900 border border-supa-700 rounded-xl w-full max-w-5xl shadow-2xl flex flex-col max-h-[90vh] animate-in zoom-in-95 duration-200">
                <div className="p-6 border-b border-supa-800 flex justify-between items-center">
                    <h3 className="text-xl font-bold text-white">Create New Table</h3>
                    <button onClick={() => setIsCreateModalOpen(false)} className="text-supa-400 hover:text-white">✕</button>
                </div>
                
                <div className="p-6 overflow-y-auto flex-1">
                    <form id="createTableForm" onSubmit={handleCreateTableSubmit} className="space-y-6">
                        <div>
                            <label className="block text-sm font-medium text-supa-300 mb-1">Table Name</label>
                            <input 
                                type="text" 
                                required
                                value={newTableName}
                                onChange={(e) => setNewTableName(e.target.value)}
                                className="w-full bg-supa-950 border border-supa-700 rounded px-3 py-2 text-white focus:border-supa-accent focus:outline-none font-mono"
                                placeholder="e.g. users_profiles"
                            />
                        </div>

                        <div>
                            <div className="flex justify-between items-center mb-2">
                                <label className="block text-sm font-medium text-supa-300">Columns</label>
                                <button type="button" onClick={addColumn} className="text-xs bg-supa-800 hover:bg-supa-700 text-supa-200 px-2 py-1 rounded transition-colors">+ Add Column</button>
                            </div>
                            
                            <div className="border border-supa-800 rounded-lg overflow-hidden">
                                <table className="w-full text-left text-xs">
                                    <thead className="bg-supa-950 text-supa-400">
                                        <tr>
                                            <th className="p-3 w-1/5">Name</th>
                                            <th className="p-3 w-1/6">Type</th>
                                            <th className="p-3 text-center">PK</th>
                                            <th className="p-3 text-center">Nullable</th>
                                            <th className="p-3 w-1/6">Default</th>
                                            <th className="p-3 w-1/4">Constraints (Unique, FK, Check)</th>
                                            <th className="p-3"></th>
                                        </tr>
                                    </thead>
                                    <tbody className="divide-y divide-supa-800 bg-supa-900">
                                        {newColumns.map((col) => (
                                            <tr key={col.id}>
                                                <td className="p-2">
                                                    <input 
                                                        type="text" 
                                                        value={col.name}
                                                        onChange={(e) => updateColumn(col.id, 'name', e.target.value)}
                                                        className="w-full bg-supa-950 border border-supa-700 rounded px-2 py-1 text-white focus:outline-none focus:border-supa-500 font-mono"
                                                        placeholder="column_name"
                                                    />
                                                </td>
                                                <td className="p-2">
                                                    <select 
                                                        value={col.type}
                                                        onChange={(e) => updateColumn(col.id, 'type', e.target.value)}
                                                        className="w-full bg-supa-950 border border-supa-700 rounded px-2 py-1 text-white focus:outline-none focus:border-supa-500 font-mono"
                                                    >
                                                        {COMMON_TYPES.map(t => <option key={t} value={t}>{t}</option>)}
                                                    </select>
                                                </td>
                                                <td className="p-2 text-center">
                                                    <input 
                                                        type="checkbox"
                                                        checked={col.isPk}
                                                        onChange={(e) => updateColumn(col.id, 'isPk', e.target.checked)}
                                                        className="rounded bg-supa-950 border-supa-700 text-supa-accent focus:ring-offset-supa-900"
                                                    />
                                                </td>
                                                <td className="p-2 text-center">
                                                    <input 
                                                        type="checkbox"
                                                        checked={col.isNullable}
                                                        onChange={(e) => updateColumn(col.id, 'isNullable', e.target.checked)}
                                                        className="rounded bg-supa-950 border-supa-700 text-supa-accent focus:ring-offset-supa-900"
                                                    />
                                                </td>
                                                <td className="p-2">
                                                     <input 
                                                        type="text" 
                                                        value={col.defaultValue}
                                                        onChange={(e) => updateColumn(col.id, 'defaultValue', e.target.value)}
                                                        className="w-full bg-supa-950 border border-supa-700 rounded px-2 py-1 text-supa-400 focus:text-white focus:outline-none focus:border-supa-500 font-mono placeholder-supa-700"
                                                        placeholder="NULL"
                                                    />
                                                </td>
                                                <td className="p-2">
                                                     <input 
                                                        type="text" 
                                                        value={col.constraints}
                                                        onChange={(e) => updateColumn(col.id, 'constraints', e.target.value)}
                                                        className="w-full bg-supa-950 border border-supa-700 rounded px-2 py-1 text-supa-300 focus:text-white focus:outline-none focus:border-supa-500 font-mono placeholder-supa-700 text-[10px]"
                                                        placeholder="UNIQUE, REFERENCES users(id)"
                                                    />
                                                </td>
                                                <td className="p-2 text-center">
                                                    <button 
                                                        type="button" 
                                                        onClick={() => removeColumn(col.id)}
                                                        className="text-supa-600 hover:text-red-400 transition-colors"
                                                        disabled={newColumns.length <= 1}
                                                    >
                                                        ✕
                                                    </button>
                                                </td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        </div>

                         <div>
                            <label className="block text-sm font-medium text-supa-300 mb-1">
                                Table Level Constraints (Advanced)
                            </label>
                            <p className="text-xs text-supa-500 mb-2">
                                Add raw SQL for composite keys, complex checks, or named constraints (e.g. <code>CONSTRAINT check_price CHECK (price &gt; 0)</code>).
                            </p>
                            <textarea 
                                value={tableConstraints}
                                onChange={(e) => setTableConstraints(e.target.value)}
                                className="w-full bg-supa-950 border border-supa-700 rounded px-3 py-2 text-white focus:border-supa-accent focus:outline-none font-mono text-xs h-20 resize-none"
                                placeholder="CONSTRAINT unique_user_project UNIQUE (user_id, project_id)"
                            />
                        </div>
                    </form>
                </div>

                <div className="p-6 border-t border-supa-800 bg-supa-950 rounded-b-xl flex justify-end gap-3">
                    <button 
                        onClick={() => setIsCreateModalOpen(false)}
                        className="px-4 py-2 text-supa-400 hover:text-white transition-colors"
                    >
                        Cancel
                    </button>
                    <button 
                        type="submit"
                        form="createTableForm"
                        disabled={creatingTable}
                        className="px-4 py-2 bg-supa-accent text-supa-950 font-bold rounded hover:bg-supa-accentDark disabled:opacity-50"
                    >
                        {creatingTable ? 'Creating...' : 'Create Table'}
                    </button>
                </div>
            </div>
        </div>
       )}
    </div>
  );
};